name: WIZ Terraform Deploy

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  deploy:
    name: Deploy to AWS using Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init 
        working-directory: tf/
      
      - name: Terraform Import EKS Cluster
        run: terraform import aws_eks_cluster.wiz-eks shar-wiz-eks
        working-directory: tf/

      - name: Terraform Plan
        run: terraform plan -var-file=env/dev/terraform.tfvars
        working-directory: tf/

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=env/dev/terraform.tfvars
        working-directory: tf/
